FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y python3-pip python3-dev git gcc dos2unix g++

COPY ./requirements.txt /src/requirements.txt
COPY ./config/logging/local.conf /src/local.conf

WORKDIR /src

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . /src

RUN dos2unix run_data_acquisition.sh
RUN chmod +x run_data_acquisition.sh
RUN dos2unix run_model.sh
RUN chmod +x run_model.sh
RUN dos2unix run_tests.sh
RUN chmod +x run_tests.sh

ENTRYPOINT ["sh"]