FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y python3-pip python3-dev git gcc dos2unix g++

COPY ./requirements.txt /app/requirements.txt
COPY ./src/helper_db.py /app/helper_db.py
COPY ./data/msia423_db.db /app/data/msia423_db.db
COPY ./config/logging/local.conf /app/local.conf

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . /app

EXPOSE 5000

ENTRYPOINT ["python3", "app.py"]